export const GET_BUSINESS_CATEGORYS_REQUEST = 'GET_BUSINESS_CATEGORYS_REQUEST';
export const GET_BUSINESS_CATEGORYS_SUCCESS = 'GET_BUSINESS_CATEGORYS_SUCCESS';
export const GET_BUSINESS_CATEGORYS_ERROR = 'GET_BUSINESS_CATEGORYS_ERROR';
